import {
  Store,
  Users,
  Stamp,
  Gift,
  QrCode,
  ContactRound,
  Trophy,
  Megaphone,
  Settings,
  Palette,
  ScanLine,
  LogOut,
  LogIn,
  Plus,
  Save,
  ImageUp,
  Trash2,
  RotateCcw,
  CircleCheck,
  TriangleAlert,
  CircleX
} from 'lucide-react'

export const Icons = {
  Business: Store,
  TotalCustomers: Users,
  StampsIssued: Stamp,
  RewardsRedeemed: Gift,
  QrStamper: QrCode,
  Customers: ContactRound,
  Rewards: Trophy,
  Campaigns: Megaphone,
  Settings: Settings,
  Branding: Palette,
  KioskMode: ScanLine,
  Logout: LogOut,
  Login: LogIn,
  Add: Plus,
  Save: Save,
  UploadLogo: ImageUp,
  RemoveLogo: Trash2,
  ResetBranding: RotateCcw,
  Success: CircleCheck,
  Warning: TriangleAlert,
  Error: CircleX
}
