import {
  Storefront,
  Users,
  SealCheck,
  Gift,
  QrCode,
  IdentificationCard,
  Trophy,
  Megaphone,
  Gear,
  Palette,
  DeviceMobile,
  SignOut,
  SignIn,
  Plus,
  FloppyDisk,
  UploadSimple,
  Trash,
  ArrowCounterClockwise,
  CheckCircle,
  Warning,
  XCircle,
} from '@phosphor-icons/react'

export const Icons = {
  Business: Storefront,
  TotalCustomers: Users,
  StampsIssued: SealCheck,
  RewardsRedeemed: Gift,
  QrStamper: QrCode,
  Customers: IdentificationCard,
  Rewards: Trophy,
  Campaigns: Megaphone,
  Settings: Gear,
  Branding: Palette,
  KioskMode: DeviceMobile,
  Logout: SignOut,
  Login: SignIn,
  Add: Plus,
  Save: FloppyDisk,
  UploadLogo: UploadSimple,
  RemoveLogo: Trash,
  ResetBranding: ArrowCounterClockwise,
  Success: CheckCircle,
  Warning: Warning,
  Error: XCircle,
}
